// HTTP test for version 2.0.
# get host-value(connect)
GET http://localhost:8081/api/zkm/data/localhost:2181

###

// create node
POST http://localhost:8081/api/zkm/data/localhost:2181
Content-Type: application/json

{
  "path": "/crud-test-node",
  "value": "value"
}

###

// update node
PUT http://localhost:8081/api/zkm/data/localhost:2181
Content-Type: application/json

{
  "path": "/crud-test-node",
  "value": "crud-test-node-update&value-update"
}

###

// delete node
DELETE http://localhost:8081/api/zkm/data/localhost:2181/crud-test-node-update

###

