// HTTP test for version 2.0.
# get host-value - WORK
GET http://localhost:8081/api/zkm/data/localhost:2181
###


// create node - WORK
POST http://localhost:8081/api/zkm/data/localhost:2181
Content-Type: application/json

{
  "path": "/t1",
  "value": "value"
}
###

// update node - WORK
PUT http://localhost:8081/api/zkm/data/localhost:2181
Content-Type: application/json

{
  "path": "/t1",
  "value": "t777&value"
}
###

// delete node - WORK
DELETE http://localhost:8081/api/zkm/data/localhost:2181/t1

###

