# get host-value - WORK
GET http://localhost:8081/api/zkm/data/localhost:2181
###

# data injection
POST http://localhost:8081/api/zkm/data/injection
Content-Type: application/json

{
  "sourceHost": "localhost:2181",
  "sourceNodePath": "/b1/b2",
  "targetHost": "localhost:2181",
  "targetNodePath": "/i1/i2",
  "updOldValues": false
}
###

# delete node
#DELETE http://localhost:8081/api/zkm/data/localhost:2181/i1/i2

#// create node - WORK
#POST http://localhost:8081/api/zkm/data/localhost:2181
#Content-Type: application/json
#
#{
#"host": null,
#"path": "/saveTest",
#"value": "saveTest"
#}
####



