#POST http://localhost:80/api/item
#
#
#### Так можно писать целую цепочку ручных тестов, как для POSTMAN, ответы выводит в терминале
##GET http://localhost:8080/api/zkm/connection/localhost:2181
#
#


POST http://localhost:8081/api/zkm/conn/create
Content-Type: application/json

{
  "host": "localhost:2181",
  "path": "",
  "value": ""
}
###

GET http://localhost:8081/api/zkm/data/host-value
Content-Type: application/json

{
  "host": "localhost:2181",
  "path": "",
  "value": ""
}
###

GET http://localhost:8081/api/zkm/conn/check
Content-Type: application/json

[
  "localhost:2181", "someTestData"
]
###
